# Generated by Django 4.1.7 on 2023-05-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('semester', models.IntegerField(max_length=1)),
                ('enrolment_no', models.CharField(max_length=11)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
