# Generated by Django 4.1.7 on 2023-05-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_alter_eventregistration_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rules',
        ),
    ]
