# Generated by Django 4.1.7 on 2023-05-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_prices_remove_event_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eligibilityFeild',
        ),
    ]
