# Generated by Django 4.1.7 on 2023-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eligibility',
            field=models.CharField(default='You must know at least 1 programming language.', max_length=1024),
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.CharField(default='Certifications and trophies will be given to first 3 rank holders.', max_length=1024),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.CharField(default='rules', max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='media/events/images/'),
        ),
    ]
