# Generated by Django 4.1.7 on 2023-05-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_eligibility_event_prize_event_rules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rules',
        ),
    ]
