# Generated by Django 4.1.7 on 2023-05-20 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='contact_no',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='semester',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
    ]
