# Generated by Django 4.2.4 on 2023-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
