# Generated by Django 4.1.7 on 2023-06-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
