# Generated by Django 4.1.7 on 2023-05-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='media/cources/images')),
                ('title', models.CharField(max_length=27)),
                ('bio', models.CharField(max_length=27)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
    ]
