# Generated by Django 4.1.7 on 2023-05-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Cources',
        ),
    ]
