# Generated by Django 4.1.7 on 2023-05-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_rename_courses_cources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cources',
            new_name='Cource',
        ),
    ]
