# Generated by Django 4.1.7 on 2023-05-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_rename_cource_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bio',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=270),
        ),
    ]
