# Generated by Django 4.1.7 on 2023-05-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_alter_course_bio_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bio',
            field=models.CharField(max_length=1024),
        ),
    ]
